"""
Healthcare task definitions and profiles.

Each HealthcareTask represents one sensing/processing job generated by a
wearable device.  Task profiles are derived from published literature on
clinical-grade biosignal processing workloads.

References:
  - ECG workload: 10-second window at 360 Hz, 16-bit depth = 3,600 samples
    × 2 bytes = 7.2 KB = 57,600 bits; arrhythmia classifier ≈ 150 M cycles
  - SpO2: simple LED-ratio algorithm, ~500 K cycles, 5 KB data
  - BP (cuffless PPG): 2 M cycles, 50 KB data
  - Multi-vital fusion: aggregated pipeline, ~8 M cycles, 1 MB data
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class HealthcareTask:
    task_id: int
    device_id: int
    timestamp: float              # arrival time in seconds since simulation start
    data_size_bits: int           # D_i — raw data payload in bits
    cpu_cycles: int               # C_i — required CPU cycles for local processing
    max_delay_s: float            # T^{max}_i — SLA deadline in seconds
    privacy_sensitivity: float    # ρ_i ∈ [0, 1] — higher → more sensitive
    ci_score: float               # Φ_i ∈ [0, 1] — Criticality Index
    attack_probability: float = 0.0   # p_{atk,i} ∈ [0, 1] — adversarial threat level
    source: str = 'synthetic'         # 'synthetic' | 'physionet' | 'mimic'
    task_type: str = 'unknown'        # key into TASK_PROFILES (e.g. 'ecg_analysis')
    assigned_node: Optional[int] = None
    actual_latency_s: Optional[float] = None
    actual_energy_j: Optional[float] = None
    sla_violated: bool = False

    def __post_init__(self):
        # Clamp CI and privacy to [0, 1]
        self.ci_score = float(max(0.0, min(1.0, self.ci_score)))
        self.privacy_sensitivity = float(max(0.0, min(1.0, self.privacy_sensitivity)))
        self.attack_probability = float(max(0.0, min(1.0, self.attack_probability)))


# ---------------------------------------------------------------------------
# Clinical task profiles
# Keys map to task type strings used by the event generator.
# Values contain base parameters before per-task noise injection.
# ---------------------------------------------------------------------------
# Cycle counts updated to literature-realistic MCU-class workloads
# (Zhang 2021, Banbury 2021 MLPerf-Tiny).  Synchronised with event_generator.
TASK_PROFILES = {
    'ecg_analysis': {
        'data_size_bits':         57_600,   # 7.2 KB = 3600 samples × 16-bit (FIX C2)
        'cpu_cycles':        150_000_000,
        'max_delay_s':              0.15,   # 150 ms clinical arrhythmia SLA (FIX C3)
        'privacy_sensitivity': 0.9,
    },
    'spo2_monitoring': {
        'data_size_bits':         40_000,
        'cpu_cycles':          5_000_000,
        'max_delay_s':               2.0,
        'privacy_sensitivity':       0.6,
    },
    'bp_analysis': {
        'data_size_bits':        400_000,
        'cpu_cycles':         30_000_000,
        'max_delay_s':               1.0,
        'privacy_sensitivity':       0.8,
    },
    'multi_vital': {
        'data_size_bits':      8_000_000,
        'cpu_cycles':        120_000_000,
        'max_delay_s':               0.8,
        'privacy_sensitivity':      0.85,
    },
}

# Default CI score per task type (used when not supplied externally)
DEFAULT_CI = {
    'ecg_analysis':    0.85,
    'spo2_monitoring': 0.4,
    'bp_analysis':     0.6,
    'multi_vital':     0.75,
}
